[package]
name = "mailbox"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "wayland", "x11"] }
axum = "0.8"
base64 = "0.22"
rand = "0.9"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
url = "2"
urlencoding = "2"
webbrowser = "1"
dotenvy = "0.15"
serde_json = "1.0.151"
anyhow = "1.0.104"
chrono = "0.4"
reqwest-eventsource = "0.6.0"
futures-util = "0.3.34"
rust-embed = "8.12.0"
unicode-segmentation = "1.13.3"
scraper = { version = "0.27.0", default-features = false }
